# Site settings
name: 张浩石
location: 北京
company: 北航
position: 博后
github: https://github.com/
facebook: https://www.facebook.com/
phone: +393331806579
email: zhs1900@gmail.com

baseurl: "/optozhs.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown
